# Generated by Django 5.1.4 on 2025-08-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
