# Generated by Django 5.1.4 on 2025-08-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_cartorderitem_coupons_cartorderitem_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('New Order', 'New Order'), ('New Review', 'New Review'), ('New Course Question', 'New Course Question'), ('Draft', 'Draft'), ('Course Published', 'Course Published'), ('Course Enrollment Completed', 'Course Enrollment Completed')], default='Draft', max_length=100),
        ),
    ]
