# Generated by Django 5.1.4 on 2025-08-25 10:36

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix=''),
        ),
    ]
