# Generated by Django 5.1.4 on 2025-08-26 08:44

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='cart_order_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='cart_order_item_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='enrolledcourse',
            name='enrollment_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='qa_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='question_answer_message',
            name='qam_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='variant_item_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='', unique=True),
        ),
    ]
